[project]
name = "fancyfetch"
version = "0.1.0"
description = "A fancy, fast system information utility!"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "json5>=0.12.0",
    "rich>=14.0.0",
]
